### ISSUE TITLE
problem with first config with xepg

### ISSUE THREAD

**Issue by thetux07** [SenexCrenshaw/xTeVe#14]
hello 
just after inslall, i made "first config with xepg, i made link of my m3u and link for epg 
https://xmltvfr.fr/xmltv/xmltv.xml
and on the last step i have this log: 
2022/08/27 16:41:03 [xTeVe] Open:                   /share/tv_channels.m3u
2022/08/27 16:41:03 [xTeVe] Check File:             /share/tv_channels.m3u
2022/08/27 16:41:07 [xTeVe] Save File:              /share/tv_channels.m3u [ID: M1WEF0TA36A5320D768O]
2022/08/27 16:41:11 [xTeVe] [WARNING] Plex can not handle more than 480 streams. Use filter to reduce the number of streams. If you do not use Plex, ignore this warning.
2022/08/27 16:41:11 [xTeVe] All streams:            66260
2022/08/27 16:41:11 [xTeVe] Active streams:         66260
2022/08/27 16:41:11 [xTeVe] Filter:                 0
2022/08/27 16:42:15 [xTeVe] Download:               https://xmltvfr.fr/xmltv/xmltv.xml
2022/08/27 16:42:31 [xTeVe] Check File:             https://xmltvfr.fr/xmltv/xmltv.xml
2022/08/27 16:42:49 [xTeVe] Save File:              https://xmltvfr.fr/xmltv/xmltv.xml [ID: X16IEKDF0X6KIN0667RQ]
2022/08/27 16:42:49 [xTeVe] XEPG:                   Parse XMLTV file: XMLTV
2022/08/27 16:43:08 [xTeVe] XEPG:                   Update database

and and nothing more happens
have you an idea ?
when i select PMS it's 
thank you

**Comment by deku-m** [comment]
Hi,

I have the same when using m3u files with alot of streams in it lets say around 50k.
Then it takes ages to "update database" but it never finish.

Is there a extra debugging mode we can enable?
[_addon_db21ed7f_xteve_logs.txt](https://github.com/SenexCrenshaw/xTeVe/files/9439419/_addon_db21ed7f_xteve_logs.txt)

**Comment by thetux07** [comment]
Thank you, you use with homeassistant or not ?

**Comment by deku-m** [comment]
> Thank you, you use with homeassistant or not ?

Yes i am

**Comment by deku-m** [comment]
Looks like big EPG files for alot of streams is having issues in this release for me.

**Comment by thetux07** [comment]
the addon for HA has been update by the develloper and it's now ok :)
thank you
