### ISSUE TITLE
[FR] Upload backup in setup screen

### ISSUE THREAD

**Issue by deku-m** [SenexCrenshaw/xTeVe#16]
**Is your feature request related to a problem? Please describe.**
WHen starting xteve for the first time you get the setup page from tuner till EPG. If you reinstall your Xteve or rebuild in docker you need to go to the process again after setting up you can restore. Might be easier to have that function in the setup as well.

**Describe the solution you'd like**
Upload function for backup file on setup..

**Describe alternatives you've considered**
Well after setting up you can upload the file thats the workaround now.

**Additional context**
N/A

**Comment by SenexCrenshaw** [comment]
If you use a volume linked to a local directory for in your docker config and do not remove the files than you should not have to reconfigure. 

``- /opt/configs/xteve/config:/home/xteve/conf``

**Comment by SenexCrenshaw** [comment]
Added this in, Its in a branch we are testing. I will merge it soon
https://github.com/SenexCrenshaw/xTeVe/pull/19

**Comment by SenexCrenshaw** [comment]
Should be good to go now
[/releases/v.2.5.2](https://github.com/SenexCrenshaw/xTeVe/releases/tag/v2.5.2)
