### ISSUE TITLE
[FR] Upload option for local file.

### ISSUE THREAD

**Issue by deku-m** [SenexCrenshaw/xTeVe#17]
**Is your feature request related to a problem? Please describe.**
ON setup it provides for m3u files a local and url option to get the streams.
But the local file needs to be uploaded in docker, or somewhere else.

**Describe the solution you'd like**
Upload form to browse on you desktop for local m3u file to choose and storage.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by SenexCrenshaw** [comment]
Its in a branch we are testing. I will merge it soon
#19

**Comment by SenexCrenshaw** [comment]
Should be good to go now
[/releases/v.2.5.2](https://github.com/SenexCrenshaw/xTeVe/releases/tag/v2.5.2)
