### ISSUE TITLE
[BUG] Cant finish setup / hang after adding XMLTV (EPG) stays at updating database

### ISSUE THREAD

**Issue by deku-m** [SenexCrenshaw/xTeVe#20]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
When filling in all the step with my IPTV url the docker build hangs and stays in Updating Database after XMLTV (EPG).
**Server (please complete the following information):**
**OS [e.g. Linux - Ubuntu]**
- Docker build 
**- xTeVe Version and Build [to be found in the xTeVe log]**
- 2.5 BUILD 1 

**To Reproduce**
1. Go to 'First time setup and follow all steps
2. Add the desired URLS'
3. After adding EPG url it hangs on Updating database.

**Expected behavior**
Finish the setup and provide the webpage

**Screenshots**
<img width="750" alt="Schermafbeelding 2022-08-30 om 21 29 17" src="https://user-images.githubusercontent.com/37069737/187526581-112c17be-10ea-4cf4-b000-a9ae41b13a3f.png">

**Desktop (please complete the following information):**

**Additional context**
For help run: /home/xteve/bin/xteve -h
2022/08/30 20:21:31 [xTeVe] [WARNING] Don't run this as Root!
2022/08/30 20:21:31 [xTeVe] Version:                2.5 Build: 1
2022/08/30 20:21:31 [xTeVe] Database Version:       2.3.0
2022/08/30 20:21:31 [xTeVe] System Folder:          /data/conf/
2022/08/30 20:21:31 [xTeVe] Load Settings:          /data/conf/settings.json
2022/08/30 20:21:31 [xTeVe] System IP Addresses:    IPv4: 2 | IPv6: 0
2022/08/30 20:21:31 [xTeVe] Hostname:               db21ed7f-xteve
2022/08/30 20:21:31 [xTeVe] Temporary Folder:       /tmp/xteve/2022-08-KHLN-NAV438/
2022/08/30 20:21:31 [xTeVe] GitHub:                 https://github.com/SenexCrenshaw
2022/08/30 20:21:31 [xTeVe] Git Branch:             main [SenexCrenshaw]
2022/08/30 20:21:31 [xTeVe] SSDP / DLNA:            true
2022/08/30 20:21:31 [xTeVe] [WARNING] Updates have been disabled by the developer
2022/08/30 20:21:31 [xTeVe] UUID:                   2022-08-KHLN-NAV438
2022/08/30 20:21:31 [xTeVe] Tuner (Plex / Emby):    1
2022/08/30 20:21:31 [xTeVe] EPG Source:             PMS
2022/08/30 20:21:31 [xTeVe] Plex Channel Limit:     480
2022/08/30 20:21:31 [xTeVe] All streams:            0
2022/08/30 20:21:31 [xTeVe] Active streams:         0
2022/08/30 20:21:31 [xTeVe] Filter:                 0
2022/08/30 20:21:31 [xTeVe] Web server:             Starting
2022/08/30 20:21:31 [xTeVe] DVR IP:                 172.30.33.18:34400
2022/08/30 20:21:31 [xTeVe] Web Interface:          http://172.30.33.18:34400/web/ | xTeVe is also available via the other 1 IP.
2022/08/30 20:22:47 [xTeVe] Download:               http://URLTOIPTV
2022/08/30 20:23:13 [xTeVe] Header filename:        tv_channels_2f8801c4e8_plus.m3u
2022/08/30 20:23:14 [xTeVe] Check File:             http://URLTOIPTV
2022/08/30 20:23:15 [xTeVe] Save File:              http://URLTOIPTV
2022/08/30 20:23:17 [xTeVe] [WARNING] Plex can not handle more than 480 streams. Use filter to reduce the number of streams. If you do not use Plex, ignore this warning.
2022/08/30 20:23:17 [xTeVe] All streams:            123443
2022/08/30 20:23:17 [xTeVe] Active streams:         123443
2022/08/30 20:23:17 [xTeVe] Filter:                 0
2022/08/30 20:23:26 [xTeVe] Download:               http://URLTOIPTV
2022/08/30 20:23:28 [xTeVe] Check File:             http://URLTOIPTV
2022/08/30 20:23:32 [xTeVe] Save File:              http://URLTOIPTV [ID: xxxxxxx]
2022/08/30 20:23:32 [xTeVe] XEPG:                   Parse XMLTV file: XMLTV
2022/08/30 20:23:35 [xTeVe] XEPG:                   Update database

For me it looks like if the EPG file is to big with a lot of information it can not handle.
The default stream file was around 60k stream too much but cleaned it up. Only the EPG can't i think and will provide all.

**Comment by SenexCrenshaw** [comment]
I have seen reports about this in the main xteve repo. I can look into it but need some files to test with.

**Comment by thetux07** [comment]
You can test with https://xmltvfr.fr/xmltv/xmltv.xml
Tins french xml tv guide

**Comment by SenexCrenshaw** [comment]
This worked fine for me. Are you getting an errors on your host?

**Comment by deku-m** [comment]
No i dont it just hangs on updating after several restarts. Stays using 50% cpu
To bad i cant share the IPTV as i use it with credentials.

[INFORMACIÓN ESTADO DO MAR MAÑÁ.zip](https://github.com/SenexCrenshaw/xTeVe/files/9467305/INFORMACION.ESTADO.DO.MAR.MANA.zip)

I also tried to upload with the new features but fails after the xmltv gets pushed then it goes into updating database and hangs

**Comment by SenexCrenshaw** [comment]
that xml file loaded fine for me. I need the m3u as well. You could just change the http links in there to something that doesnt work so you can share with me. Otherwsie this works fine for me.
Are you running in docker?

**Comment by deku-m** [comment]
> that xml file loaded fine for me. I need the m3u as well. You could just change the http links in there to something that doesnt work so you can share with me. Otherwsie this works fine for me.
> Are you running in docker?

Yes I am running it as docker.  I will check if i can adjust the file.
It difficult there is no extended debugging somewhere

**Comment by SenexCrenshaw** [comment]
You could run it locally from code. If you know visual code its not too bad. From there you can see what is going on in the code.

As far as the M3U you could open it up in a program like notepad++ and replace all the http://<whatever> with a fake url.

**Comment by deku-m** [comment]
Hereby attached the m3u file with http://<removed> i tested it in docker and still says update database im confused why i have this.

[tv_channels_2f8801c4e8_plus.zip](https://github.com/SenexCrenshaw/xTeVe/files/9475083/tv_channels_2f8801c4e8_plus.zip)

**Comment by SenexCrenshaw** [comment]
Excellent. I am testing now and it looks like its just a matter of time. the parsing is slow. I am going to look to optimize it. I will keep you posted.

**Comment by deku-m** [comment]
> Excellent. I am testing now and it looks like its just a matter of time. the parsing is slow. I am going to look to optimize it. I will keep you posted.

Well at mine it doesnt really finish in the docker container xD
I had it running for more then 8 hours

**Comment by SenexCrenshaw** [comment]
I found the problem routine and will spend some time to optimize it.

**Comment by SenexCrenshaw** [comment]
I fixed the issue of the db creation but the webpage will be unresponsive now. its >12k channels. I think this might be a one off and I am not going to peruse debugging further. Id say this use case isnt best for you. Maybe use something like epg.best to clean things up.

**Comment by deku-m** [comment]
> I fixed the issue of the db creation but the webpage will be unresponsive now. its >12k channels. I think this might be a one off and I am not going to peruse debugging further. Id say this use case isnt best for you. Maybe use something like epg.best to clean things up.

Meaning the stream m3u list needs to be smaller then 12k? It is strange in the old 2.2.0 it worked for me.

**Comment by SenexCrenshaw** [comment]
Fixed in #40

**Comment by SenexCrenshaw** [comment]
Thanks for that insight. I found the code which was causing the web site issue. I fixed that. So anything with 2000+ and no filters wont show up in the mapping view.

**Comment by SenexCrenshaw** [comment]
lmk if this fixed your issue
