### ISSUE TITLE
Add playlist wide option to keep channel names the same as source.

### ISSUE THREAD

**Issue by mytee12** [SenexCrenshaw/xTeVe#25]
**Is your feature request related to a problem? Please describe.**

Currently, If the name of the channel changes on the source side it is not updated for the channel in xTeVe. I see there is an option per channel to use  regex to keep single channels updated. I personally do not use xTeVe to manage channel names or EPG, just as a proxy.

**Describe the solution you'd like**
In the playlist section under a particular playlist, when clicking it, i would like there to be a option that is along the lines of "Sync all channel names with Playlist source"

**Describe alternatives you've considered**
Currently, I am just deleting and re-adding my playlist which has the desired affect but if it was automatic it would be great.

**Addtional comments**
 adding option of something like "always use EPG ID of Playlist source" might be helpful too if for instance if there was no EPG for a channel then later it was added so you would no longer need to use Dummy EPG and rather use the new EPG ID. Maybe this is already being done?

Essentially on each update I just want to clone everything from the source, apart from adding Dummy EPG for channels without a valid one.

**Comment by SenexCrenshaw** [comment]
Fixed in #44 . Not sure if it covers your additional comments but this will update the channel name if the M3U file changes.

**Comment by mytee12** [comment]
Syncing channel names works as expected. Thank you!

**Comment by SenexCrenshaw** [comment]
w00t!
