### ISSUE TITLE
Port suddendly added to every URLs

### ISSUE THREAD

**Issue by Write** [SenexCrenshaw/xTeVe#29]
It seems after a recent update all urls in the M3U got the port added to the url (34400), but I use a reverse proxy since forever so it just broke my setup,

Anyway to disable that ?

Thanks

**Comment by SenexCrenshaw** [comment]
Yep. Ill add a switch in for that

**Comment by Write** [comment]
Thanks !

**Comment by SenexCrenshaw** [comment]
Added in #36. I published new bin/docker files as well. LMK if it works for you

**Comment by Write** [comment]
Seems working ! Thanks
