### ISSUE TITLE
Unable to change Logo

### ISSUE THREAD

**Issue by clshtws** [SenexCrenshaw/xTeVe#37]
**Describe the bug**
Configuration doesn't save the 'Logo URL' regardless of what's entered.

**Server (please complete the following information):**
- Linux 5.15.26-gentoo
- Arch amd64 `Intel(R) Xeon(R) CPU E5-2697 v4`
- xTeVe Version 2.5.2 (Binary from GitHub Release)

**To Reproduce**
1. Once logged into xTeVe, navigate to the 'Channel' section
2. Select/Click a channel highlighted in red. Configuration Modal should open.
3. Update the 'Logo URL' by either using the new 'Use M3U Logo' button, or entering a Custom URL.
4. Click 'Done' at the bottom of the Configuration Modal.

**Expected behavior**
New Logo should appear in Channel List.

**Screenshots**
Screen-Record can be found here - https://gfycat.com/basicabsoluteisopod

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Browser Brave/Chromium
 - Version 1.43.89, 105.0.5195.102 

**Additional context**
I was unable to find any correlating error messages in xTeVe's command-line output, or the browser's DevTools!

**Comment by iceman73** [comment]
I compiled the latest version for Docker, and I am still having this logo issue as described here

**Comment by iceman73** [comment]
I found a work around.

Click use M3U Logo
Cut the URL from the "Logo URL:"
Press the Tab Key so goes back to the unknown logo
paste the url you cut above into "Logo URL:"
Press Tab key,

The Logo now updates to the proper one
