### ISSUE TITLE
Error when using FFmpeg as a buffer

### ISSUE THREAD

**Issue by jdelek** [SenexCrenshaw/xTeVe#46]
Whenever I use FFmpeg as a stream buffer, I get this error: http: panic serving x.x.x.x:53292: interface conversion: *osfs.OsFS is not avfs.VolumeManager: missing method VolumeAdd
This error is thrown multiple times and stream data is never passed to the client. This error only occurs on the latest build (2.5.2) , 2.5.1 works fine with FFmpeg as the stream buffer.

- Windows 
- amd64
- 2.5.2

**Comment by martinreedau** [comment]
Same issue here when using xTeve as the stream buffer. Arm64, docker, 2.5.2

**Comment by thetux07** [comment]
+1 i have the same issue

2022/09/18 16:30:43 [xTeVe] Buffer:                 true [xteve]
2022/09/18 16:30:43 [xTeVe] Buffer Size:            5120 KB
2022/09/18 16:30:43 [xTeVe] Channel Name:           ****
2022/09/18 16:30:43 [xTeVe] Client User-Agent:      VLC/3.0.11 LibVLC/3.0.11
2022/09/18 16:30:43 http: panic serving 172.30.33.10:36086: interface conversion: *osfs.OsFS is not avfs.VolumeManager: missing method VolumeAdd
goroutine 458 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x835b80, 0xc0024bc8a0})
	/usr/local/go/src/runtime/panic.go:890 +0x262
xteve/src.checkVFSFolder({0xc017abdb40, 0x34}, {0x9f76d8, 0xc0001621b0})
	/src/src/toolchain.go:64 +0x79
xteve/src.bufferingStream({0xc013470978, 0x14}, {0xc02592f380, 0x3f}, {0xc01401b0b0, 0xd}, {0x9f1760, 0xc0011c2700}, 0xc005b3c200)
	/src/src/buffer.go:75 +0x390
xteve/src.Stream({0x9f1760, 0xc0011c2700}, 0xc005b3c200)
	/src/src/webserver.go:231 +0x69e
net/http.HandlerFunc.ServeHTTP(0xc01e929af0?, {0x9f1760?, 0xc0011c2700?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x9f1760, 0xc0011c2700}, 0xc005b3c200)
	/usr/local/go/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xc0024bc660?}, {0x9f1760, 0xc0011c2700}, 0xc005b3c200)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0262dab40, {0x9f1c20, 0xc01a112630})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db

**Comment by thetux07** [comment]
Hello 
No News for this problem ?
Thank you

**Comment by SenexCrenshaw** [comment]
I will look into this
