### ISSUE TITLE
Mapping - Shift Channels, Unable to turn off

### ISSUE THREAD

**Issue by mLgz0rn** [SenexCrenshaw/xTeVe#48]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
I seem to be unable to disable Shift Channels, when ever I save and go back into Mapping, it's enabled again.

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]: Unraid 6.11.0 (Docker)
- Arch [e.g. Intel 64 Bit]: amd64
- xTeVe Version and Build:  2.5.2 Build: 2

**To Reproduce**
1. Go to Mapping
2. Disable Shift Channels
3. Save

**Expected behavior**
I expected it to leave the option disabled after being saved.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 11 
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 106.0.5249.91

**Comment by SenexCrenshaw** [comment]
I will look into this

**Comment by mLgz0rn** [comment]
> I will look into this

Thank you.
I'm actually unsure if it does turn it on/off and its just a ui glitch.
I have tried to look but have been unable to find it, does this feature have a setting in the config (settings) file?

**Comment by SenexCrenshaw** [comment]
You are right, it is not saved. I think this is a miss and will add it in
