### ISSUE TITLE
Can't get past setting Number of Tuners

### ISSUE THREAD

**Issue by Deanosim** [SenexCrenshaw/xTeVe#5]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Can't get past the setting the number of tuners in the initial setup page

**Server (please complete the following information):**
- OS [Unraid Docker]
- Arch [Intel 64 Bit]
- xTeVe Version and Build [2.5.1]

**To Reproduce**
Download and start container, open web interface and try to set number of tuners, and get the following error in the browser console.
I tried, 2 different browsers and incognito and got the same error on both.
```
Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at createLayout (menu_ts.js:703:52)
    at ws.onmessage (network_ts.js:87:13)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4834976/186723327-5e3cdde8-ed2e-44a2-88b4-259f658a5783.png)

**Comment by SenexCrenshaw** [comment]
Fixed. Sorry about that.
