### ISSUE TITLE
XMLTV only works with UTF-8 XML files

### ISSUE THREAD

**Issue by bphillips09** [SenexCrenshaw/xTeVe#54]
**Describe the bug**
XMLTV only works with UTF-8 XML files

**Server (please complete the following information):**
Linux/macOS/Windows
xTeVe Version and Build: Latest

**To Reproduce**
1. Import an XMLTV file that's not UTF-8 and will see an error like: 
"xml: encoding "ISO-8859-1" declared but Decoder.CharsetReader is nil"

**Expected behavior**
The file should load normally.

**Additional context**
This can be fixed by replacing 
`err = xml.Unmarshal(body, &xmltv)` and `err = xml.Unmarshal(content, &xmltv)` 
with something like
```
decoder := xml.NewDecoder(bytes.NewReader(body))
if strings.Contains(string(body), "encoding=\"ISO-8859-1\"") {
	decoder.CharsetReader = charset.NewReaderLabel
}
err = decoder.Decode(&xmltv)
```
Note that with this fix you'll also need to import `"bytes"` and `"golang.org/x/net/html/charset"`

**Comment by SenexCrenshaw** [comment]
Should be good to go now
