### ISSUE TITLE
Tapiosinn's TV logo repository was shutdown by GitHub, repository now located at GitLab

### ISSUE THREAD

**Issue by cnorton-dev** [SenexCrenshaw/xTeVe#55]
His TV Logo repository got shut down on GitHub, it is now on GitLab and can be found at https://gitlab.com/tapiosinn/tv-logos/ as I am no longer using xTeVe I just wanted to share this information so it can be updated accordingly.

**Comment by SenexCrenshaw** [comment]
Fixed a few days ago in pr #52 

Thank you for the heads up!
