### ISSUE TITLE
Tapiosinn's tv-logos Github repository down

### ISSUE THREAD

**Issue by Till1012** [SenexCrenshaw/xTeVe#56]
**Describe the bug**
Xteve is not able to find station logos from Tapiosinn's tv-logos Github repository. 
[Tapiosinn's tv-logos Github repository](https://github.com/Tapiosinn/tv-logos/) seems to be gone.

**Server (please complete the following information):**
- OS Ubuntu Server 22.04
- Arch amd64
- xTeVe Version 2.5.3 (3)

**Additional context**
Maybe swap to Fourqui's [fork](https://github.com/Fourqui/tv) of Tapiosinn's tv-logos.

Thx for your work so far!

**Comment by SenexCrenshaw** [comment]
Grab the latest release. It was fixed the day it broke.
