### ISSUE TITLE
Tapiosinn's tv-logos **GitLab** repository is also now down

### ISSUE THREAD

**Issue by gtronset** [SenexCrenshaw/xTeVe#57]
Describe the bug
Xteve is not able to find station logos from the updated  [Tapiosinn's tv-logos "new" GitLab repository](https://gitlab.com/tapiosinn/tv-logos), which was recently set to be used instead of [Tapiosinn's tv-logos Github repository](https://github.com/Tapiosinn/tv-logos/) in 

Both repo's for Tapiosinn's tv-logos seem to be gone, and there's a corresponding message on http://tv-logos.com/ (redirects to https://justpaste.it/5pstq):

> Unfortunately Gitlab has chosen to take the same action as Github, and remove my repository because of high bandwidth use. This is probably the end I'm afraid, unless I get enough support to get my own hosting.

---

Server (please complete the following information):

- Docker
- amd64
- xTeVe Version 2.5.3 (latest)

**Screenshots**

<img width="1218" alt="Screen Shot 2022-11-04 at 3 43 17 PM" src="https://user-images.githubusercontent.com/4139605/200085321-bfbb87f0-bdda-4d8b-aa3a-c0ef3ce29508.png">

Additional context
Maybe swap to Fourqui's [fork](https://github.com/Fourqui/tv) of Tapiosinn's tv-logos. Since this appears to be a game of "whack-a-mole", perhaps also consider allowing the repo to be set in the UI (via input box, etc.)? That way another fork can be set dynamically as needed?

Thanks for the help!

**Comment by SenexCrenshaw** [comment]
UGH. I wonder if tar should be hosted somewhere and just DL them all. This is becoming a cumbersome

**Comment by gtronset** [comment]
Right, or allow for a local version to be loaded and people can either fork, download, or otherwise provide the files?

**Comment by SenexCrenshaw** [comment]
I think the local version is the best bet. I would have to build a function for each site type (API) hosted if not.
