### ISSUE TITLE
Looping Buffer (ffmpeg and vlc)

### ISSUE THREAD

**Issue by JRGonz** [SenexCrenshaw/xTeVe#60]
#### Please first read the [documentation](https://github.com/xteve-project/xTeVe-Wiki/blob/master/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

Using a HDHR and recording one channel while watching another eventually leads to the buffer looping over and over. The HDHR feed seems to die and xteve just keeps sending previous segments to the client (in my case: plex). Playback to client loops. Recording fails and eventually cuts off anything past this point. 

**Server (please complete the following information):**
- OS Proxmox / Debian
- Arch Ryzen 3700x (x64)
- xTeVe 2.5.3

**To Reproduce**
1. Schedule recording on channel x. 
2. While recording watch something on channel y. 
3. Wait a few minutes. It usually happens within 20-30 minutes
4. Buffer will loop on both feeds to clients. 

**Expected behavior**
To watch one channel while recording another. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Plex Web Client, iOS / iPadOS Plex app, Apple TV Plex app
 - Browser Firefox 107.0.1 MacOS
 
**Additional context**
I have seen this also happen while simply watching 1 channel. I tried changing every option I could to try to sort it out. I figured maybe this may be a hangup from the HDHR but I've seen this happen using iptv as well. I am really not even sure where to look It seems xteve related since I've never had this problem having the HDHR connected directly to plex.

**Comment by SenexCrenshaw** [comment]
I am working on a new version which should address this issue. Stay tuned!

**Comment by bolagnaise** [comment]
> I am working on a new version which should address this issue. Stay tuned!

Any update on this. XTEVE has been busted for years because of this bug.

**Comment by SenexCrenshaw** [comment]
https://github.com/SenexCrenshaw/StreamMaster

It's in alpha now. There is a discord with updates. Check the discussions for the link.

**Comment by SenexCrenshaw** [comment]
https://hub.docker.com/repository/docker/senexcrenshaw/streammaster/general

Its a nice release. The backend proxy is stable and the UI is working nicely. some odds and ends need to be worked out but i dont need iptveditor or xtevie anymore.

**Comment by Gigoo25** [comment]
> https://hub.docker.com/repository/docker/senexcrenshaw/streammaster/general
> 
> Its a nice release. The backend proxy is stable and the UI is working nicely. some odds and ends need to be worked out but i dont need iptveditor or xtevie anymore.

Is the discord still available? It seems like the link provided on "https://github.com/SenexCrenshaw/StreamMaster" is expired.
