### ISSUE TITLE
Web interface no longer showing up

### ISSUE THREAD

**Issue by Write** [SenexCrenshaw/xTeVe#9]
Using your fork since day one, added `senexcrenshaw/xteve:latest`few days ago when a docker build was available, today watchtower updated xteve and the web interface won't show up anymore.

No error in console, and xteve seems to be running just fine, but since the webserver is not reachable, nothing actually work from outside.

Port 34400 is used and always worked, curl localhost:34400 from the host just echoes `curl: (56) Recv failure: Connection reset by peer` which doesn't really help.

I really have no idea what happened.

```
2022/08/25 21:26:28 [xTeVe] Version:                2.5 Build: 1
2022/08/25 21:26:28 [xTeVe] Database Version:       2.3.0
```

Restarting the container doesn't solve the issue

Web interface ine doesn't show up anymore on boot. Nothing about web interface on boot. Maybe because I forced change the hostname ? The new feature worked great the other day

EDIT : I'm trying to find what makes the web interface to not launch, for now it seems to be as soon as there's m3u file in the config file. I don't know why.

**EDIT 2 (Found the issue) : 
Ok it seems I found the issue, I grabbed a playlist locally from an unavailble playlist (tvheadend). Xteve just never timed out and the responding webserver neither (tvheadend crashed really hard), so it was simply stuck on "Download" indefinitely. Thus never going to the next step which would've been starting the webserver**

**Comment by SenexCrenshaw** [comment]
Glad to here. I will close this out. Let me know if you want any features.
